### PR TITLE
Revert "fix for issue 72"

### PR DESCRIPTION
**Pull request by ankur-1989**
Reverts ABenchM/abm-frontend#197

### CODE REVIEW

**Comment by ankur-1989** [comment]
need to revert this change as this change does not pass BsNavbarComponent test case.

**Comment by ankur-1989** [comment]
@mac24079 just approve and merge this change as this pull request will revert your changes from develop branch. you need to pass the BsNavbarComponent test case also after making your changes .

**Comment by mac24079** [comment]
@ankur-1989 
I approved the changes but I only changed the HTML and CSS file, for that also I need to write the test case you mean?

**Comment by ankur-1989** [comment]
@mac24079 No, you don't need to write test case it is already there. you just need to check why is it failing after incorporating your changes.

**Pull request merged**
