### PR TITLE
Public collection page conversion from bootstrap to angular material

### PR DESCRIPTION
**Pull request by Minal0110**
---
name: Public collection component converted from bootstrap to angular material
about: Removed search functionality and replace it with filter were collection are searched
---

Pull request related to issue #209 
A issue was raised to make all tables consistent which means conversion of bootstrap tables to angular material. And this pull request is for specific component i.e. home.component

**List of functionalities contained in this pull request**
Below functionalities are implemented for Public collection and Pinned collection tables
2 Angular material tables 
Pagination 
Sorting
Filtering
Pin/Unpin rows

Note:  Filter option for search collection is added instead of Search button for public collection table.

Below is the screenshot of all passed test cases also containing home.component test cases 
homecomponent-testcases

### CODE REVIEW

**Comment by ankur-1989** [comment]
@Minal0110 This PR has conflicts. could you please check ?

**Comment by Minal0110** [comment]
@ankur-1989 PR conflicts are resolved.

**Comment by ankur-1989** [comment]
@Minal0110 
I took the fresh copy of this branch still on ng test it is giving me following error - 
image

**Comment by Minal0110** [comment]
Hi @ankur-1989 
Could please check PR now. Following are the passed test cases
passedtestcase

**Pull request merged**
