### PR TITLE
Manage public collection

### PR DESCRIPTION
**Pull request by TalalE**
---
name: manage public collection
about: Create a new component that take care of delete , activate and deactivate public collections.
---
**Related issue and description**
Issue #131 :Implement 'Manage Public Collections' page for admin 

Backend branches:
#303 anitha_getallcollectionchanges
#310 deletepubliccollections

**List of the Functionalities**
deleteSelectedCols(colIDs: String) : Delete single collection or list of collections.
changeColStatus(coll: Collection) : Activate or deactivate public collection.

**List of the test cases**
1.Component ManagePublicCollection is created.
2.Checkbox click should select a row.
3.Check if DeleteSelectedCols Button invoke 
test is running
deleteColsDialog which open a dialog to confirm the delet process.
4.Check if apply filter event is called correctly.

### CODE REVIEW

**Comment by ankur-1989** [comment]
Hi, 
public collections are not coming in manage public collections 
page , you need to fix the JpacollectionDao findcollections method in backend - as we can not make collections public collection will always be private only its versions will be public so to get the public collections you need to make changes in the query.

**Comment by vishaljcj** [comment]
@ankur-1989 As per what we had discussed so far in ABM meetings, a collection will remain private only if all its versions are private. Even if a single version in a collection is made public, then the status of the collection would change to public by default. @nguyenLisa could you please provide your view on this, as this has to be addressed in the upcoming milestones.

**Comment by vishaljcj** [comment]
@nguyenLisa could you please provide your suggestion on this.

**Comment by nguyenLisa** [comment]
Hi,
Collections should not be public nor private: their versions can be public or private. As soon as a version is made public, the collection's name and description is of course disclosed to the public as well. But there is no use keeping track of whether a collection is public or not.
Does that make sense?

**Comment by TalalE** [comment]
@ankur-1989 
Display only public versions.
Delete version instead of collection.

image

**Comment by ankur-1989** [comment]
I took the fresh copy of this branch and ran the ng test still one test case is getting failed - 
image

**Comment by vishaljcj** [comment]
@ankur-1989 fixed now. PFB screenshot of all passing test cases

image

**Comment by ankur-1989** [comment]
@TalalE 

Two things -
Deactivate button - does not look like a button. Please check.

image

When I click on show versions then a list of versions come but the arrowhead is still in the downward direction. Instead, it should change its direction on button click. Please check.

image

**Comment by TalalE** [comment]
@ankur-1989  Both are updated. Please check.

**Pull request merged**
