### PR TITLE
fixed develop branch

### PR DESCRIPTION
**Pull request by mac24079**
Develop branch is broken at the moment. This merge requests for fixing the same.

### CODE REVIEW

**Comment by mac24079** [comment]
Sure. I'll add them to the .gitignore file. Can you please confirm where the pagination is showing only 1 page? When searching for the projects on the collection page I am still able to see different pages using the paginator. I am attaching the same for the reference. Is this you are referring?
reference
ing?

**Comment by ankur-1989** [comment]
for me , for the same query it is showing following results

image

**Comment by ankur-1989** [comment]
you might have to re raise the pull request as this request consists of package-lock.json file

**Comment by mac24079** [comment]
I deleted the file from here. This will work. If not I'll close this and raise another request. Kindly let me know.
Thanks.

**Pull request closed without merging**
