### PR TITLE
Admin_Manage_Users changes

### PR DESCRIPTION
**Pull request by vishaljcj**
---
This pull request contains the code changes for Admin/User login, Registration and Manage Users(for admin)
---

**Is your pull request related to an issue? Please describe.**
This pull request covers point 1 of #53 

**List of functionalities contained in this pull request**
User/Admin login
Registration form 
Lock/Unlock user accounts for admin
Delete user accounts for admin
Change UserRole for admin

**List of the test cases**
Test cases have been written for the newly implemented component(manage-users) and its corresponding newly implemented service(user service). Besides this, some existing spec.ts files have been modified in order to include all dependencies.

__Note: Lock/UNlock, Delete and Change UserRole related backend changes have been not pushed to develop yet. They can be tested from 'abmpgdevelop' branch in abm repository. These changes are still being pushed as most of them are contained within the same file.
Also the links for 'Forgot password', 'User Profile', 'Manage Public Collections' and 'Pending Requests' wont work, as the corresponding changes will be pushed along with the subsequent PRs._

### CODE REVIEW

**Comment by ankur-1989** [comment]
Hi Vishal,
Please find attached the log file. There are a lot of linting errors in the application. I guess you are not using the pre-commit hook for the linting check.

[linterrors.log](https://github.com/ABenchM/abm-frontend/files/2625780/linterrors.log)

**Comment by vishaljcj** [comment]
Hi Ankur, are you checking 'Vishal_MIlestone2' branch? The error log shows errors for components such as 'Pending Requests', 'User Profile' etc. which are not present in this branch. However there are some linting errors in this branch, which I will fix and commit.

**Comment by vishaljcj** [comment]
@ankur-1989 fixed the errors in this branch. Please check.

**Comment by ankur-1989** [comment]
Hi, 
I used abmpgdevelop branch for backend as mentioned in the description.
Please find below the review comments :- 

1. All files are passing linting issues.
2. Normal User login and logout is working
3. Registeration form is working, There is one thing which we can change in the successful registration message - 
image
Initial letter t of this should be captial and remove the redundant fullstop from the end of the sentence.
4. Lock/Unlock user is working fine.
5. I could not change the role of the user. It is not working as it says method not found in the backend.
6. Could not delete the user account. It did not throw any error.
7. I checked the responsiveness of the pages but it does not work well. I have attached two screenshots below for examples.
If we look at the screenshots, when I open the page in mobile's screen size then pages does not render properly. Menu also disappears. There is one sort of menu button but it does not work.

image

image
8. All the written test cases are passing. But I did not find the test cases for the following functionalities 
1. Lock/Unlock user 
2. Change Role User
3. Delete User Account

**Comment by vishaljcj** [comment]
@ankur-1989 Hi, PFB the addressed review points
3. This has been fixed.
5 & 6. Change User role and DElete Users functionalities are working perfectly fine for me when tested with abmpgdevelop branch in the backend. There are no errors thrown. Change userRole works fine-- user role gets updated in the DB. For DEleteUsers, a warning box is shown initially for confirmation, and if clicked on yes, the corresponding user account is deleted. Could you please test this once again.
7. Some changes have been done with respect to  responsiveness in such a way that some elemnts are not displayed when opened in mobile screen resolution. And as for the menu disappearing issue, this already exists in the develop branch for other pages. I can open a separate issue for the same, and this doesn't have to be pushed along with this PR. Does it work for you?
8. The missing test cases have been added.

**Comment by ankur-1989** [comment]
Hi, 
Now the manageUsers page itself is not coming. I am logging in with UserAdmin user.
BR,
Ankur

**Comment by vishaljcj** [comment]
@anut347 Could you please check getUsername method in UserController.java. This method doesnt return the user role now, and because of that the issue mentioned in the previous comment is occuring.

**Comment by anut347** [comment]
Hi Vishal,

Yes there seems to be some issue because of the series code reverts that happened last week. 
The code changes made to return the role are lost now.
Will fix it in some time and comment. Sorry for the trouble

**Comment by anut347** [comment]
https://github.com/ABenchM/abm/pull/284.
Pull request created for the same

**Comment by vishaljcj** [comment]
closing this pull request so that the same can be raised with code changes that fits into the new structure for abm-frontend

**Pull request closed without merging**
