### PR TITLE
tooltip is added to affiliation field

### PR DESCRIPTION
**Pull request by Chinmay-92**
tooltip is added to affiliation field to get helpful information.
A Basic info message is added inside tooltip for now.

issue #44 fixed

### CODE REVIEW

**Comment by Chinmay-92** [comment]
Yes, we added basic info message because we didn't understand what affiliation is in this context.
Could you please provide appropriate info message so that I will fix it.

**Comment by nguyenLisa** [comment]
The affiliation is basically the university/company a researcher belongs to. For example for me, it used to be Fraunhofer IEM. It is now Paderborn University since a few weeks back.

**Comment by ankur-1989** [comment]
I think It would be nice to use a placeholder for this field. No need to go and check the tooltip. When you are coming from the top of the form, it is already visible what he/she has to do. Less efforts for the user.

**Comment by ankur-1989** [comment]
closing this pull request as another one has been opened.

**Pull request closed without merging**
