### PR TITLE
Unify admin styles

### PR DESCRIPTION
**Pull request by TalalE**
---
name: Unify admin styles
The admin components should have only one css file.
---

Issue #277 
The following components of the admin pages should have same css file.
 Manage public collection.
Manage users.
Pending request.

unify styles

### CODE REVIEW

**Comment by ankur-1989** [comment]
@TalalE 

I created two public collections but when I go to manage public collections page it does not show any collection. Please check.

image
image

**Comment by TalalE** [comment]
@ankur-1989 
Did you make the version Public?

**Comment by TalalE** [comment]
Manage Public collections view shows public versions.

**Comment by ankur-1989** [comment]
Yes please check the public collections screenshot.

**Comment by ankur-1989** [comment]
@TalalE 
Could you please raise this PR again with the latest develop changes? 
 as this is giving some error while opening admin pages

**Comment by iamebuka** [comment]
@TalalE could you please resolve the conflicting files

**Comment by vishaljcj** [comment]
#330 has been raised for the same. Hece closing this

**Pull request closed without merging**
