### PR TITLE
check if username exists fixed

### PR DESCRIPTION
**Pull request by Chinmay-92**
if username already exists,it won't allow to register with same username. 
Register components are updated with error handling.

### CODE REVIEW

**Comment by Chinmay-92** [comment]
Hi @ankur-1989, I merged new develop branch into feature branch. 
Please check now it should be running properly.

**Comment by ankur-1989** [comment]
@Chinmay-92 I pulled your code and tried running the application but I am getting an error. So when I hit the submit button on Register form, it is giving me 500 server error. Could you please check?

**Comment by ankur-1989** [comment]
@Chinmay-92  Sorry, I was not aware of the addition of new column in the user table and the SQL script is also not updated in the docs folder on GitHub. I have one more doubt if the table is not updated with the new column then how did you guys manage to get the latest table and able to run this change. anyhow, now I have updated the SQL script with the latest column. Now I am able to run your change and it is working fine.

**Comment by Chinmay-92** [comment]
@ankur-1989 on submit we just checked for response false i.e. "User is already in use" scenario and handled similar error on UI (registration form)
cc: @ishwaryaPaderborn  and @vishaljcj 
Please verify and let me know if something is not working

**Comment by Chinmay-92** [comment]
I was able to submit the request successfully for registration form locally.
I didn't have to update my user table in local db.

**Comment by ankur-1989** [comment]
ok. Surprised. Could you please check if you have the approval_token column in user table?  Anyway, I am merging the pull request.

**Pull request merged**
