### PR TITLE
Feat/fix 218

### PR DESCRIPTION
**Pull request by mac24079**
Pull request
about: Add asterisk(*) to the mandatory fields on the Login page.
Is your pull request related to an issue? Please describe.
Yes. Issue #218

### CODE REVIEW

**Comment by ankur-1989** [comment]
Hi Mohit,

You have not written any test case for this. Is that possible if you could write one test case for this?
Best Regards,
Ankur Gupta

**Comment by mac24079** [comment]
Hello @ankur-1989 ,

Do you mean to say writing test case for the component itself? Means for the login component?

Thanks.

**Comment by ankur-1989** [comment]
No for this change.

**Comment by mac24079** [comment]
Closing this one and will open a new request for the same with the test-case inclusion.

Thanks.

**Pull request closed without merging**
