### PR TITLE
Fix/feat 72

### PR DESCRIPTION
**Pull request by mac24079**
Fix for issue #72 ---
name: Pull request
about: Suggest a change in the code of this project
There was no navigation before when changing the tabs.

**Is your pull request related to an issue? Please describe.**
Yes. Issue #72 
**List of functionalities contained in this pull request**
Highlighted tab is active on moving when navigating the tabs.

**List of the test cases**
No change in the .ts file and fixed error - affecting the other test cases due to the code change.

### CODE REVIEW

**Comment by ankur-1989** [comment]
Hi, 
image

Now the navbar is coming as given in the image. Is that possible to make it like the previous version?
The only change that should be there is to highlight the current tab.

Best Regards,
Ankur Gupta

**Comment by mac24079** [comment]
@ankur-1989 
yes, we will be keeping this styling, but can you please tell me from where that image was taken as the application shows the ABM logo on the left side, but I am testing it on two different PC's one with on the laptop and other to a big screen monitor but it somehow comes like this in both the develop and frontendpg branch.

image



image


Thanks.

**Comment by nguyenLisa** [comment]
Hi @mac24079 

The styling I see on your screenshots looks nice. Would it be possible to add a background color and and remove the black border like so?

capture d ecran 2018-11-25 a 17 00 25

Thanks.

**Comment by mac24079** [comment]
@ankur-1989 
Also, I just checked the ABM logo is on the left side in the frontendpg branch but in the develop branch the logo is still on the right side. Does the code has been tested by copying/pasting to the frontendpg branch?? If that is the case I can make it work for the frontendpg branch as well

**Comment by mac24079** [comment]
@nguyenLisa 

Yeah, that is also possible. Any color preferences?

**Comment by mac24079** [comment]
1.
image

2.
image

@nguyenLisa 
I added this but just as an opinion of mine the one with the borders look more clear/descriptive. But we can keep any of them.

**Comment by nguyenLisa** [comment]
@mac24079 thanks! Perhaps a lighter blue (like the ABM logo: 45D9F6) would be nicer and give the same visibility as the frame.

**Comment by mac24079** [comment]
Openend a new merge request for the same. https://github.com/ABenchM/abm-frontend/pull/219.
Hence, closing this one.

**Pull request closed without merging**
