### PR TITLE
Delete collection bug#325

### PR DESCRIPTION
**Pull request by TalalE**
---
name: Delete public collection if last version is deleted
about: Delete public collection if last version is deleted in manage public collection view
---

#325
Fix the error of deleting version in manage public collection page if there is only one version in that collection.

#277
Fix the issue of unify admin pages style in one css file.

deleteSingleCol(versionID: String)
Delete the entire public collection if the deleted version was the last version in that collection.

test

### CODE REVIEW

**Comment by iamebuka** [comment]
@TalalE since this pull request includes PR 278, I will advise you close PR 278.

**Comment by iamebuka** [comment]
@TalalE none of the delete buttons(for deleting public versions) in the manage public collection controller works, could you look into that, please?

**Comment by vishaljcj** [comment]
@iamebuka I just tested this now, and the delete buttons work fine for me. Could you please check this once again after doing a pull. If you still face any issue, could you please share some screenshots or console logs.

**Comment by TalalE** [comment]
yes sure.

**Comment by iamebuka** [comment]
LGTM

**Pull request merged**
