### PR TITLE
Changes for registration, main navigation bar, user/admin login, lock/unlock user, change user role

### PR DESCRIPTION
**Pull request by vishaljcj**
This pull request has been created in reference to the previous PR #222 . It includes the changes for registration, main navigation bar, user/admin login, lock/unlock user, change user role. Delete users functionality has not been pushed in this PR(corresponding LOC have been commented out) since the corresponding backend changes have not yet been pushed. All the remaining functionalities can be tested with the develop branch of abm-backend.

_(N.B For main navigation bar changes, major contributions done by @TalalE ._)

Attached below is the screenshot of all passing test cases.
image

### CODE REVIEW

**Comment by ankur-1989** [comment]
@vishaljcj ,
In this pull request #241 changes were made for Registration page and asterisk was put at the last of the label. Please incorporate those changes or put your changes on the top of this pull request. 

Best Regards,
Ankur Gupta

**Comment by nguyenLisa** [comment]
and please update the screenshot :)

**Comment by vishaljcj** [comment]
@ankur-1989 @nguyenLisa done. PFB the screenshot
image

**Comment by ankur-1989** [comment]
Hi, 
Please find the review comments as per the mentioned functionality.

Registration - 
I was able to register the user. But, the pending lists page is not working therefore could not approve the user. I did not understand the use of Activation link as for me it does not open anything.

Main Navigation bar- 

1. I found that in navigation bar, when we shift from one tab to another tab it changes color but when I shifts to demo (User tab) it does not show any color for the User tab. As far as I remember, It was changed and pushed to develop branch through this pull request [https://github.com/ABenchM/abm-frontend/pull/236]

In this change :- 
image

In Develop branch:- 
image

User/Admin Login:- 
Normal and UserAdmin user is able to login into the application.

other mentioned functionalities are also working fine.

**Comment by vishaljcj** [comment]
@ankur-1989 
For registration, the changes for pending requests page have not been pushed along with this PR. So for testing you will have to use the activation link sent to admin mail. Clicking on this link doesn't show anything in the UI, but the user would be approved. You can check the same in the DB.

The navigation bar issue has been fixed now.

PFB the screenshot of all passing test cases.
image

**Comment by ankur-1989** [comment]
@vishaljcj 
I tried the same but it was not working.

**Comment by ankur-1989** [comment]
I did not get the errors but it did not approve the user too.

**Comment by vishaljcj** [comment]
@ankur-1989 Changing the host address from  **https://abm.cs.upb.de**/rest/approval?name.. to  **http://localhost:8080**/rest/approval?name... should approve the user. It worked for me. I am not exactly sure why it isn't working for you. Besides this functionality is in the develop branch of ABM backend and is not related to the front-end code changes that have been pushed in this PR. Could you please approve this PR, if all other things are working fine, so that subsequent pull requests for other functionalities related to Milestone 1 & 2 can be raised.

**Comment by nguyenLisa** [comment]
Sorry @vishaljcj , but as said before, we can't let code that is not working in develop. Let's first fix the approval issue here. @ankur-1989 , could you try what @vishaljcj proposed and let us know if that works for you?

**Comment by ankur-1989** [comment]
Hi, 
Yeah got it. Now it is working. I'll approve the request.
Thanks!!

**Pull request merged**
