### PR TITLE
issue #32 fixes

### PR DESCRIPTION
**Pull request by ishwaryaPaderborn**
create collection component added with stub

### CODE REVIEW

**Comment by ishwaryaPaderborn** [comment]
screenshot from 2018-05-27 18-10-46

Please check the attached screenshot. And let us know if this required output.

**Comment by ankur-1989** [comment]
If possible try to align the Show Filtering options button along with search button as you can see in current production version. Rest is fine.

**Comment by ishwaryaPaderborn** [comment]
We have made all the requested changes. 

screenshot from 2018-05-28 14-40-39

**Comment by ankur-1989** [comment]
Everything looks fine to me now. I don't know if that is part of your issue, but,  when I type in query box then search button should get enabled. If this is not part of your issue then we are good to go.

**Comment by ishwaryaPaderborn** [comment]
We have made changes so that 'Search' button will enable when some text is entered.

**Pull request merged**
